[package]
name = "polyvinyl-acetate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
diesel = { version = "1.4.4", features = ["postgres"] }
dotenv = "0.15.0"
rocket = "0.5.0-rc.1"
rand = "0.8.5"
diesel_migrations = "1.4.0"