FROM ekidd/rust-musl-builder:stable AS builder

COPY . .
RUN --mount=type=cache,target=/home/rust/.cargo/git \
    --mount=type=cache,target=/home/rust/.cargo/registry \
    --mount=type=cache,sharing=private,target=/home/rust/src/target \
    sudo chown -R rust: target /home/rust/.cargo && \
    cargo build --release && \
    cp target/x86_64-unknown-linux-musl/release/web ./web

FROM alpine
COPY --from=builder /home/rust/src/web .
USER 1000

ARG DATABASE_URL 
ENV DATABASE_URL=$DATABASE_URL

ARG RABBIT_URL
ENV RABBIT_URL=$RABBIT_URL

ENV ROCKET_ADDRESS="0.0.0.0"

CMD ["./web"]