apiVersion: apps/v1
kind: Deployment
metadata:
  name: pvac-worker
  namespace: default
  annotations:
    "sidecar.jaegertracing.io/inject": "true"
spec:
  selector:
    matchLabels:
      pvac: worker
  template:
    metadata:
      labels:
        pvac: worker
    spec:
      containers:
      - name: pvac-worker
        image: pvac-worker
        imagePullPolicy: Never